# Generated by Django 5.2 on 2025-06-03 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_delete_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("sleep", "睡眠时长(小时)"),
                            ("stand", "站立时长(小时)"),
                            ("calorie", "卡路里(kcal)"),
                            ("steps", "步数"),
                        ],
                        max_length=10,
                        verbose_name="数据类型",
                    ),
                ),
                ("value", models.FloatField(verbose_name="数值")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "手动输入"), ("device", "设备同步")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "健康数据",
                "verbose_name_plural": "健康数据记录",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "data_type"],
                        name="accounts_he_user_id_8c72fb_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="accounts_he_timesta_22ce7e_idx"
                    ),
                ],
            },
        ),
    ]
