# Generated by Django 5.2 on 2025-06-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_healthdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="calorie",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sleep",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stand",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="steps",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="HealthData",
        ),
    ]
