# Generated by Django 5.2 on 2025-06-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_calorie_userprofile_sleep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="target_calorie",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_sleep",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_stand",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="target_steps",
            field=models.IntegerField(default=0),
        ),
    ]
