# Generated by Django 5.2 on 2025-06-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0006_userprofile_target_calorie_userprofile_target_sleep_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="total_progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="target_calorie",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="target_sleep",
            field=models.IntegerField(default=0),
        ),
    ]
